### PR TITLE
Minor Ontology Fixes + New Classes

### PR DESCRIPTION
**Pull request by gtfierro**
Addresses some different tag issues, including removing the `owl:AllDifferent` classification. Adding classes requested in #205, #199 and from prior (offline) conversations

### CODE REVIEW

**Comment by corymosiman12** [comment]
Hi Gabe - I realize this might not be able to make it into the v1.2 release, but we came up with a bunch of point types that seemed relevant. I can move this to another issue if you'd rather get it out of this PR?

- [ ] Cooling_Tower_Fan_Enable_Command
- [ ] Cooling_Tower_Fan_Run_Status
- [ ] Cooling_Tower_Fan_Speed_Command
- [ ] Cooling_Tower_Fan_Speed_Sensor
- [ ] Cooling_Tower_Fan_Frequency_Sensor
- [ ] Cooling_Tower_Fan__Failure_Alarm
- [ ] Cooling_Tower_Fan_Run_Time_Sensor
- [ ] Cooling_Tower_Fast_Fan_Enable_Command
- [ ] Cooling_Tower_Slow_Fan_Enable_Command
- [ ] Cooling_Tower_Makeup_Water_Flow_Sensor
- [ ] Cooling_Tower_Makeup_Water_Valve_Command
- [ ] Cooling_Tower_Basin_Temperature_Sensor
- [ ] Cooling_Tower_Basin_Water_Level_Sensor
- [ ] Cooling_Tower_Basin_Water_Level_Alarm
- [ ] Cooling_Tower_Basin_Fill_Valve_Command
- [ ] Cooling_Tower_Basin_Water_Heater_Status
- [ ] Condenser_Water_Isolation_Valve_Command
- [ ] Condenser_Water_Isolation_Valve_Status
- [ ] Condenser_Water_Bypass_Valve_Position_Command
- [ ] Condenser_Water_Bypass_Valve_Position_Sensor
- [ ] Cooling_Tower_Blowdown_Water_Flow_Sensor
- [ ] Cooling_Tower_Blowdown_Valve_Command
- [ ] Condenser_Water_Thermal_Power_Sensor
- [ ] Condenser_Water_Pump_Enable_Command
- [ ] Condenser_Water_Pump_Run_Status
- [ ] Condenser_Water_Pump_Speed_Command
- [ ] Condenser_Water_Pump_Speed_Sensor
- [ ] Condenser_Water_Pump_Run_Time_Sensor
- [ ] Condenser_Water_Differential_Pressure_Sensor
- [ ] Condenser_Water_Differential_Pressure_Setpoint
- [ ] Outside_Air_Wet_Bulb_Temperature_Sensor

**Comment by gtfierro** [comment]
We can definitely add those in to v1.2, though they are probably best done as a new PR. I think  for all the point names w/ an equipment type in there (e.g. `Cooling_Tower_xyz`), they are better modeled by a `brick:isPointOf` relationship between the point and the equip. For example, all of the `Fan` points should be separated out, and then we introduce the equip class of a `Cooling Tower Fan`

**Comment by corymosiman12** [comment]
Hey @gtfierro - just began working on this (branched off `v1.2-release`). So the `Cooling_Tower_Fan` class exists. There appear to be instances where the equipment-type_point-type exists (i.e. `Exhaust_Fan_Enable_Command`).  Are you saying that we should expand this out as well, or is the recommendation to not add new 'equipment-specific' points, and instead use a generic point type (`Enable_Command`) and the equipment type (`Cooling_Tower_Fan`)?

**Comment by gtfierro** [comment]
The equipment-type_point-types should be expanded out where possible, and we should avoid adding equipment-specific points where the point type is something that may be associated with different types of equipment

**Pull request merged**
