### PR TITLE
add floor number

### PR DESCRIPTION
**Pull request by corymosiman12**

### CODE REVIEW

**Comment by corymosiman12** [comment]
hey @gtfierro do you think you will be able to get this into the v1.2 release?

**Comment by gtfierro** [comment]
Possibly! Can you add a description of why these need to be modeled and an example of how they would be used in a model? Even if they are not included in the immediate v1.2 release, they can appear in subsequent v1.2.x releases

**Comment by corymosiman12** [comment]
FloorNumber is a common entity property for floors (knowing where things are located). Having a standardized nomenclature for how to number floors (i.e. ground floor is 0) is also important.

```turtle
:floor-1 a brick:Floor ;
    brick:hasFloorNumber 1 .
```

**Comment by corymosiman12** [comment]
@gtfierro descriptions and examples added. lmk if anything else

**Comment by corymosiman12** [comment]
@gtfierro where should I add a new PR?

**Pull request closed without merging**
