### PR TITLE
v1.4.1 Release

### PR DESCRIPTION
**Pull request by gtfierro**
PR gathering the changes for Brick v1.4.1

### CODE REVIEW

**Comment by sarahmacSE978** [comment]
I have some suggestions on REC classes to replace the Brick classes that currently don't have replacements:

brick:Detention_Room 
brick:Environment_Box -> rec:Laboratory
brick:Field_Of_Play -> rec:OutdoorSpace
brick:First_Aid_Room -> rec:TreatmentRoom
brick:Freezer
brick:Gatehouse
brick:Hospitality_Box
brick:Hot_Box
brick:Information_Area -> rec:Reception
brick:Lighting_Zone  
brick:Loading_Dock -> rec:LoadingReceivingRoom
brick:Majlis-> rec:Lounge
brick:Media_Room -> rec:RecordingRoom
brick:Media_Hot_Desk -> rec:RecordingRoom
brick:Media_Production_Room -> rec:RecordingRoom
brick:Outside -> rec:OutdoorSpace
brick:Parking_Level
brick:Parking_Structure
brick:Prayer_Room -> rec:MeditationRoom
brick:Pump_Room -> rec:UtilitiesRoom
brick:Riser
brick:Sports_Service_Room -> rec:ExerciseRoom
brick:Stage_Riser
brick:TETRA_Room -> rec:TelecommunicationRoom
brick:Ticketing_Booth
brick:Tunnel
brick:Water_Tank
brick:Vertical_Space -> rec:ElevatorShaft

For the Brick location entities that don't have replacements, what are your thoughts on adding the replacement with generic rec:Room?

**Comment by sarahmacSE978** [comment]
Also, it is difficult to tell in the PR if the following REC classes are added:

rec:Lounge
rec:Teamroom
rec:Lobby

**Comment by gtfierro** [comment]
Issues to raise with REC:
- missing classes in the .ttl release like `rec:Lounge`. This appears in their [online docs](https://dev.realestatecore.io/ontology/Space/Architecture/Room/Lounge), but isn't in the .ttl file . Can these be updated?

**Comment by sarahmacSE978** [comment]
We discovered another inconsistency in Brick v1.4.0:

These 2 classes are missing subCLassOf so we don't have the parent class:
brick:EV_Charging_Hub
brick:Horizontal_Fan_Coil_Unit

We can infer based on equivalent classes.

**Comment by sarahmacSE978** [comment]
Hi!  I checked the generated .ttl output and the rec replacements for Brick location classes look good.  I see only a few more issues:

1.There are still missing REC classes:

rec:Lounge
rec:Teamroom
rec:Lobby

For each I'm expecting to see:

rec:<ClassType> a rdfs:Class,
        sh:NodeShape ;
    rdfs:label "<ClassName>"^^xsd:string ;
    rdfs:subClassOf rec:Room .


2. I've identified a few more brick location classes that are missing REC replacements:

brick:Ablutions_Room -> rec:Room
brick:Hazardous_Materials_Storage -> rec:Storage

3. You mentioned in a previous meeting that you didn't think rec:ElevatorShaft was a good equivalent to brick:Vertical_Space, do you want to replace rec:Room instead?

brick:Vertical_Space -> rec:ElevatorShaft & change to rec:Room?

Thanks!

**Pull request merged**
