### PR TITLE
Fix: properties inside restrictions are not converted

### PR DESCRIPTION
**Pull request by shreyasnagare**
```
:myclass rdfs:subClassOf [ a owl:Restriction ;
            owl:onProperty brickframe:hasPoint ;
            owl:someValuesFrom brick:Change_Filter_Alarm ] .
```
should be converted to 
```
:myclass rdfs:subClassOf [ a owl:Restriction ;
            owl:onProperty brick:hasPoint ;
            owl:someValuesFrom brick:Change_Filter_Alarm ] .
```
Ref: #125

### CODE REVIEW

**Comment by shreyasnagare** [comment]
@gtfierro I'm sure both branches have all the latest changes. I think this has something to do with the changes made to `py-brickschema`.

**Comment by gtfierro** [comment]
Hmmmm ok. Changes to py-brickschema *shouldn't* have affected these tests but it looks like they are. Good catch! I'll dig into this

**Comment by gtfierro** [comment]
@shreyasnagare looks like the tests are failing because `brickschema` incorporated the latest release of Brick, for which the Brick unit tests were not updated. This is a dependency loop in our development process that we'll need to smooth over. I'll submit the changes to Brick in a separate PR, you can merge that in to this branch (assuming my PR fixes the issue) and that should solve these issues.

**Comment by gtfierro** [comment]
@shreyasnagare can you merge from master and see if your tests are passing now?

**Comment by shreyasnagare** [comment]
@gtfierro Tests are passing now.

**Pull request merged**
