### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by gtfierro**
* hasRepresentation (#318)
* SHACL-based Brick Implementation (#341)
* adding documentation on Brick releases (#264)
* Class-based shapes (#240)
* Fix Nightly Builds (#241)
* Amending QUDT Definitions (#239)
* Update Ontology Metadata (#245)
* amend definition for isPointOf (#251)
* Adding quantities, sensor classes for air quality (#247)
* use brick value, not brick area inside the entity property (#254)
* Regenerate air quality sensor example (#255)
* generalizing solar panel and adding its subclasses (#248)
* add building electrical meter example (#265)
* Fixing Meter relationship in example (#266)
* add types to external properties and classes (#267)
* Fixing ASHRAE reference (#268)
* Fix the rest of the rdfs:seeAlso URI encoding (#275)
* Added Water Level Alarms (#282)
* Added Lockout and Availability Status Points (#280)
* added flow sensors points (#279)
* Added New Boiler Types (#283)
* Additional air handling unit types (#274)
* Update pre-commit configuration (#286)
* added air system classes (#278)
* fix bad merge: remove exhaust air system (#288)
* Radiant system terminal unit classes (#270)
* Add Shapes to Brick distribution (#285)
* PV Systems and Entity Properties (#273)
* Updating Nightly Builds (#289)
* use "/" suffix for sosa namespace (#295)
* add imbalance sensors (#293)
* add stage riser; update riser defn (#296)
* value of path should be sh:class, not rdfs:range (#300)
* Add testing for examples (#299)
* Add UFAD and diffuser equipment and points (#297)
* Fixing validation of entity properties (#301)
* remove reference to defunct tags.py file (#303)
* Add collection types (#269)
* Adding Differential Quantities to Brick (#294)
* V1.2.1 release (#309)
* added diff temp points and water temp setpoints (#277)
* Added Differential Pressure Points (#276)
* make sure we do not add duplicate RDFS labels (#307)
* remove controls (#310)
* Allow Entity Properties to have generic numeric values (#311)
* Expand ApplicableUnits annotations (#306)
* - Add Chilled Beam and subclasses (#302)
* Fix RDFS Labels (#313)
* Added brick:Relief_Damper, brick:Relief_Fan and tag:Relief (#312)
* Adding optimized SHACL shapes to reduce inference time (#316)
* Reduce automated test time (#320)
* Add Sensors from NREL Example Models (#317)
* Labels on properties and entity properties (#322)
* Fix spelling (#323)
* Ignore generated files (#327)
* fix Dew_Point to Dewpoint (#338)
* add misc concepts (#335)
* restructure valve hierarchy and add TMV (#333)
* remote incorrect tags (#340)
* add miscellaneous alarms (#331)
* add missing points (#329)
* add CRAH (#342)
* Update files generated from source (#326)
* Added heating, cooling enable commands (#339)
* Remove second skos:definition for Brick#Building (#343)

Co-authored-by: Jason B. Koh <jbkoh@users.noreply.github.com>
Co-authored-by: Carlos Duarte <cduarte@berkeley.edu>
Co-authored-by: Gabe Fierro <gfierro@nrel.gov>
Co-authored-by: wcrd <11898748+wcrd@users.noreply.github.com>
Co-authored-by: David Waterworth <wateda@gmail.com>
Co-authored-by: David Waterworth <david.waterworth@cim.io>
Co-authored-by: Jonas Bülow <jonas.bulow@se.com>
Co-authored-by: Jonas Bülow <jonas.bulow@gmail.com>

### CODE REVIEW

**Comment by jbkoh** [comment]
How is `bacnet.ttl` created? Is it an import from bacpypes or somewhere else? Or did Gabe manually create it? We should note the source inside the file for future references (e.g., for the purpose of updating and fixing the file later.)

**Comment by jbkoh** [comment]
Why do we limit the types of BACnet properties used for BACnetReferences into the few? BACnetReference can be a placeholder for any standard properties in BACnet.
(Sorry that I raise those questions now. I should've done this in #318 )

**Comment by gtfierro** [comment]
BAcnet.ttl is a draft form of the BACnet standard translated into RDF/SHACL created by @JoelBender . Once the draft form is accepted as a standard distribution of BACnet in some way, we can refer to that official source. Until then, while it has already been fairly stable, I can take care of updating it in the same way that I take care of updating QUDT.

The types of BACnet properties are not limited in the definition; the `BACnetReference` shape merely requires that a certain number of properties be included in order to facilitate interaction with that object over the BACnet network.

**Comment by jbkoh** [comment]
Cool. Thanks for the info! I will report bugs and questions to Joel then.

Could you explain why we introduce `BACnetReference` instead of directly using `bacnet:StandardObject`? Given bacnet.ttl is (semi-)stable, we can just use the shapes and the classes in the file.

**Comment by gtfierro** [comment]
@epaulson @jbkoh here's some draft release language:

---

Brick v1.3.0 is the result of more than a year of work by the Brick development team and a growing community of international contributors. This release of Brick contains several major
improvements and changes since Brick v1.2.1 as well as a number of bug fixes and smaller additions.

The big features in Brick v1.3.0 are:
- moving from an OWL-based ontology to a SHACL-based ontology. This allows Brick and Brick tooling to make use of the validation features of SHACL, which will
help to ensure that Brick models are consistent and valid. We recommend using the [pySHACL project](https://pypi.org/project/pyshacl) to conduct validation of
Brick models. The [brickschema package](https://brickschema.readthedocs.io/en/latest/) also provides support for validation
- ref:hasExternalReference is a new relationship that relates Brick entities to their representations in other digital forms, for example IFC models, BACnet networks
and timeseries databases. This builds on work on the [ref-schema](https://github.com/gtfierro/ref-schema), a new RDF schema for standardizing these external references
- ability to model meter/submeter hierarchies, their relationships to devices and rooms, and the data they produce
- dramatically expanded sets of entity properties, capturing "nameplate" and other static characteristics of Brick entities
- adding useful semantic annotations to all Brick Point classes with the brick:hasSubstance and brick:hasQuantity properties
- unit tests added to all Brick [examples](https://github.com/BrickSchema/Brick/tree/master/examples) to ensure they are up-to-date with correct Brick usage
- additional classes covering, among other thigns, different kinds of fans, sensors, PV systems

Many of these major features are documented at https://docs.brickschema.org/ .

**Comment by jbkoh** [comment]
I believe we intended to have https://github.com/BrickSchema/Brick/pull/246 in 1.3.0, didn't we?

**Comment by jbkoh** [comment]
@gtfierro  Yes, I think we agreed on all the items as in the last note, as far as I recall.

**Comment by epaulson** [comment]
We should be sure to add lastKnownValue to the release notes!

**Pull request merged**
