### PR TITLE
Fix Deprecation Statements

### PR DESCRIPTION
**Pull request by gtfierro**
Ensure that the deprecated concepts are not always asserted to be `owl:Class`

### CODE REVIEW

**Comment by gtfierro** [comment]
@steveraysteveray I attempted to fix the issue with deprecated concepts where some of the substances were asserted as owl Classes. Can you double check that the generated Brick file [here](https://gist.github.com/gtfierro/d51703811e23c34326ed4e636f4126a2) doesn't exhibit those issues? Thanks! I've spot checked it myself

**Comment by steveraysteveray** [comment]
Will do. Might not be till next week though because I have babysitting duties this week.

**Comment by gtfierro** [comment]
> Will do. Might not be till next week though because I have babysitting duties this week.

No rush! Thanks :)

**Comment by steveraysteveray** [comment]
This seems to have fixed things. All good.

**Pull request merged**
