### PR TITLE
add more location classes

### PR DESCRIPTION
**Pull request by epaulson**
Includes location classes, mostly as defined in the comment from #190 

I added a few new intermediate classes for media rooms, for service rooms, for storage rooms, and for teleco rooms. I slipped in a few new classes for telcos, and renamed 'kitchen' to be 'office kitchen' which is what I think we meant. I'll try to go back through the original issue and update the comment

### CODE REVIEW

**Review by gtfierro — CHANGES_REQUESTED** [review]
Thanks @epaulson! Do you think that `Location_Portfolio` counts a location? I could see this being an external term for now --- we haven't yet taken a position on what administrative/organizational structures should make their way into Brick yet.

A separate issue is how to rectify subclasses of a Building with the Energy Star "building primary function" classification (https://github.com/BrickSchema/Brick/blob/v1.2-release/bricksrc/entity_properties.py#L122). I can work on a way of making them equivalent, which should solve the issue

**Comment by epaulson** [comment]
For Location Portfolio, I did think that it usually has some kind of geographic connotation but might not follow a strict geopolitical boundary (and might have weird overlaps).  In that sense, it is a "location"

I think we need some kind of location "container" and 'portfolio' lines up with what some of the energy management lit uses, so that's where we got it from. 

If we want to think this one through a bit more we can take it out and revisit post 1.2

**Comment by corymosiman12** [comment]
I like the concept of portfolio outside of just a location. I agree with @epaulson that a Portfolio may have a geographic connotation, but I think that a portfolio is generally just a grouping of buildings or properties based on some lens of interest. I don't know exactly what that makes it, though.

**Comment by gtfierro** [comment]
I created #233 to capture the discussion about collection/groups of entities. I suppose that if an HVAC Zone is a location, then a Portfolio may also be a location as well, but I'd like to have a dedicated discussion about it so that we can be sure we are modeling similar concepts in similar ways. @epaulson would you be alright with removing `Location_Portfolio` for now so I can merge this and we can discuss how to include that in #233 ?

**Comment by epaulson** [comment]
Removed Location Portfolio.

**Review by gtfierro — APPROVED** [review]
Thanks @epaulson!

**Pull request merged**
