### PR TITLE
Include external ontology dependencies in the Brick+extensions build

### PR DESCRIPTION
**Pull request by gtfierro**
- RealEstateCore: `https://w3id.org/rec`
- QUDT: `http://qudt.org/2.1/schema/qudt`
- others? maybe `ref-schema`, eventually `barnet`

### CODE REVIEW

**Comment by ektrah** [comment]
I think I'd prefer if external dependencies were imported rather than included. For convenience, a Brick release could include a .zip file in addition to Brick.ttl and Brick+extensions.ttl with all the imported Turtle documents.

**Comment by gtfierro** [comment]
Thanks for the idea! I should be able to set this up so we have all of the options available, including packaging separate Turtle files in a single Zip

**Comment by gtfierro** [comment]
- also include the SHACL graph?

**Comment by gtfierro** [comment]
@JoelBender is there a new BACnet ontology I should be using?

@hammar I couldn't find an authoritative namespace for REC; http://w3id.org/rec just redirects to the REC website instead of an ontology file. I can mirror the copy of the ontology from the GitHub files easily enough but wanted to know if there was a preferred way?

Thanks both of you!

**Comment by hammar** [comment]
Hi,

REC4 is not yet formally released as GA and thus doesn't have W3ID redirect. That needs to be resolved ASAP as I'm hoping for a release this week or next. I'll get on it and update here as soon as sorted.

Karl

**Comment by gtfierro** [comment]
@hammar thanks! I may merge this PR earlier just so we have it but it will be a simple enough task to import REC once that is released

**Comment by hammar** [comment]
I just got a PR in to w3id for REC4, see https://github.com/perma-id/w3id.org/pull/3117/files

The URIs will be `https://w3id.org/rec#Concept` (redirecting to latest version) or `https://w3id.org/rec/4.0#Concept` (redirecting to a specific version). Content negotiation is employed such that `Accept: text/turtle` gets the Turtle version and anything else gets the docs pages. At the moment both Turtle file and docs used are prelease, but they'll be updated as soon as we ship.

**Comment by steveraysteveray** [comment]
Just wanted to mention that I cannot test this branch because of the following error:
```
(brickvenv) ➜  Brick git:(gtf-handle-dependencies) ✗ python generate_brick.py
Traceback (most recent call last):
  File "/Users/steveray/repositories/Brick/generate_brick.py", line 7, in <module>
    import ontoenv
ModuleNotFoundError: No module named 'ontoenv'
```

**Comment by gtfierro** [comment]
@steveraysteveray You will need to install the https://pypi.org/project/ontoenv/ package (this is in `requirements.txt` but you can also `pip install ontoenv`

**Comment by steveraysteveray** [comment]
Thanks, that helped. I notice that in this branch, the file Brick+extensions.ttl is no longer getting generated. Is this by design? Not yet fixed?

**Comment by steveraysteveray** [comment]
Also, many warnings/errors about not being able to resolve lots of graphs (presumably for importing):
```
2023-02-10:09:55:05,242 WARNING [__init__.py:137] Could not load https://brickschema.org/schema/1.0.2/BrickTag (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>); trying to resolve locally
2023-02-10:09:55:05,243 ERROR   [__init__.py:199] Could not resolve https://brickschema.org/schema/1.0.2/BrickTag (No definition for https://brickschema.org/schema/1.0.2/BrickTag)
...
2023-02-10:09:55:23,907 ERROR   [__init__.py:199] Could not resolve http://www.w3.org/2004/02/skos/core (No definition for http://www.w3.org/2004/02/skos/core)
2023-02-10:09:55:26,740 WARNING [__init__.py:137] Could not load http://qudt.org/2.1/schema/qudt (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>); trying to resolve locally
...
many more...

**Comment by gtfierro** [comment]
Weird...I'm able to reliably generate that file on this branch. Would you be able to post the full trace of the warnings and errors you were seeing (maybe in a gist or something)? The tool is (by default) very verbose about what it is trying to do when resolving the imports in the files it discovers; I should probably reduce this so that actual errors are more visible because most of the warnings are benign

**Comment by steveraysteveray** [comment]
@gtfierro, [Here's](https://gist.github.com/steveraysteveray/adac958c024fdef0a2e28b03535f4619) a gist of my terminal session. New brickvenv, on this branch. Only generated brick.ttl, not the extensions.

**Comment by gtfierro** [comment]
> @gtfierro, [Here's](https://gist.github.com/steveraysteveray/adac958c024fdef0a2e28b03535f4619) a gist of my terminal session. New brickvenv, on this branch. Only generated brick.ttl, not the extensions.

Thanks -- the error looks to be that your computer is failing to resolve some SSL certificates. I see you are running Python 3.10 so I wouldn't expect you to hit some older errors where Python wasn't managing certs correctly.

I tried reproducing this error on a fresh VM and couldn't get the SSL error to show up.

One thing to try is to upgrade the `certifi` Python package; can you try `pip install --upgrade certifi` or its equivalent in your environment?

**Comment by steveraysteveray** [comment]
Hmm. Tried your suggestion, plus some brew things. Still not working. I'm not getting this error in the master branch, just in gtf-handle-dependencies. Is that expected?

**Comment by gtfierro** [comment]
The error is related to handling import statements, which is functionality we are introducing in this branch rather than the master branch, so I do think that makes some sense.

Did you end up trying something like https://stackoverflow.com/questions/68275857/urllib-error-urlerror-urlopen-error-ssl-certificate-verify-failed-certifica ?

**Comment by steveraysteveray** [comment]
Thanks! I had tried the pip install certifi directly, which hadn't worked, but for whatever reason, the script you pointed to solved the SSL problem, and generate_brick.py now generates Brick.extension.ttl again, albeit with many error messages about the imports:
```
2023-02-13:16:15:41,157 WARNING [__init__.py:137] Could not load https://brickschema.org/schema/1.0.2/BrickTag (HTTP Error 404: Not Found); trying to resolve locally
2023-02-13:16:15:41,157 ERROR   [__init__.py:199] Could not resolve https://brickschema.org/schema/1.0.2/BrickTag (No definition for https://brickschema.org/schema/1.0.2/BrickTag)
2023-02-13:16:15:41,301 WARNING [__init__.py:137] Could not load https://brickschema.org/schema/1.0.2/BrickFrame (HTTP Error 404: Not Found); trying to resolve locally
2023-02-13:16:15:41,301 ERROR   [__init__.py:199] Could not resolve https://brickschema.org/schema/1.0.2/BrickFrame (No definition for https://brickschema.org/schema/1.0.2/BrickFrame)
2023-02-13:16:15:51,574 WARNING [__init__.py:137] Could not load https://w3id.org/bot-0.3.2 (HTTP Error 404: Not Found); trying to resolve locally
2023-02-13:16:15:51,574 ERROR   [__init__.py:199] Could not resolve https://w3id.org/bot-0.3.2 (No definition for https://w3id.org/bot-0.3.2)
2023-02-13:16:15:51,769 WARNING [__init__.py:137] Could not load https://brickschema.org/schema/Brick (https://brickschema.org/schema/Brick:1:0: not well-formed (invalid token)); trying to resolve locally
2023-02-13:16:15:51,769 ERROR   [__init__.py:199] Could not resolve https://brickschema.org/schema/Brick (No definition for https://brickschema.org/schema/Brick)
2023-02-13:16:15:59,823 WARNING [__init__.py:137] Could not load http://qudt.org/2.1/schema/extensions/imports (http://qudt.org/2.1/schema/extensions/imports:1:1: not well-formed (invalid token)); trying to resolve locally
2023-02-13:16:15:59,823 ERROR   [__init__.py:199] Could not resolve http://qudt.org/2.1/schema/extensions/imports (No definition for http://qudt.org/2.1/schema/extensions/imports)
2023-02-13:16:16:03,704 WARNING [__init__.py:137] Could not load http://qudt.org/2.1/schema/qudt (http://qudt.org/2.1/schema/qudt:1:1: not well-formed (invalid token)); trying to resolve locally
2023-02-13:16:16:04,325 WARNING [__init__.py:137] Could not load http://qudt.org/2.1/vocab/prefix (http://qudt.org/2.1/vocab/prefix:1:1: not well-formed (invalid token)); trying to resolve locally
2023-02-13:16:16:04,325 ERROR   [__init__.py:199] Could not resolve http://qudt.org/2.1/vocab/prefix (No definition for http://qudt.org/2.1/vocab/prefix)
2023-02-13:16:16:04,917 WARNING [__init__.py:137] Could not load http://qudt.org/2.1/vocab/quantitykind (http://qudt.org/2.1/vocab/quantitykind:1:1: not well-formed (invalid token)); trying to resolve locally
2023-02-13:16:16:06,146 WARNING [__init__.py:137] Could not load http://qudt.org/2.1/vocab/dimensionvector (http://qudt.org/2.1/vocab/dimensionvector:1:1: not well-formed (invalid token)); trying to resolve locally
2023-02-13:16:16:06,146 ERROR   [__init__.py:199] Could not resolve http://qudt.org/2.1/vocab/dimensionvector (No definition for http://qudt.org/2.1/vocab/dimensionvector)
2023-02-13:16:16:06,663 WARNING [__init__.py:137] Could not load http://qudt.org/2.1/vocab/sou (http://qudt.org/2.1/vocab/sou:1:1: not well-formed (invalid token)); trying to resolve locally
2023-02-13:16:16:06,663 ERROR   [__init__.py:199] Could not resolve http://qudt.org/2.1/vocab/sou (No definition for http://qudt.org/2.1/vocab/sou)
2023-02-13:16:16:19,845 WARNING [__init__.py:137] Could not load http://data.ashrae.org/bacnet/2020 (HTTP Error 404: Not Found); trying to resolve locally
2023-02-13:16:16:22,646 WARNING [__init__.py:137] Could not load http://qudt.org/2.1/schema/qudt (http://qudt.org/2.1/schema/qudt:1:1: not well-formed (invalid token)); trying to resolve locally
2023-02-13:16:16:23,405 WARNING [__init__.py:137] Could not load http://data.ashrae.org/bacnet/2020 (HTTP Error 404: Not Found); trying to resolve locally
```

I noticed in Brick.extension.ttl, the owl:imports statements point to strings ("URI") rather than \<URI\>.
```
    owl:imports "http://data.ashrae.org/bacnet/2020",
        "http://qudt.org/2.1/schema/qudt",
        "http://www.w3.org/ns/shacl" ;
```

**Comment by gtfierro** [comment]
Oops! The literal -> URI fix should be in the latest commit.

I'll be sure to add an FAQ to `ontoenv` about that error. Glad the fix worked!

**Comment by steveraysteveray** [comment]
A further request, and a question.

**The request:**
Could you update your copies of QUDT from 2.1.12 to 2.1.24? Yours are over a year old, and the current version of QUDT has refactored the closure graph, changed the default schema to SHACL, and lots of other things. For Brick, I would suggest the following files as a minimum: (do these go in the "support" folder?)
[VOCAB_QUDT-UNITS-ALL-v2.1.ttl](https://github.com/qudt/qudt-public-repo/blob/main/vocab/unit/VOCAB_QUDT-UNITS-ALL-v2.1.ttl)
[VOCAB_QUDT-QUANTITY-KINDS-ALL-v2.1.ttl](https://github.com/qudt/qudt-public-repo/blob/main/vocab/quantitykinds/VOCAB_QUDT-QUANTITY-KINDS-ALL-v2.1.ttl)
[SCHEMA-FACADE_QUDT-v2.1.ttl](https://github.com/qudt/qudt-public-repo/blob/main/schema/SCHEMA-FACADE_QUDT-v2.1.ttl). (this file tells you whether to load OWL or SHACL, with SHACL being the new default)
[SCHEMA_QUDT_NoOWL-v2.1.ttl](https://github.com/qudt/qudt-public-repo/blob/main/schema/shacl/SCHEMA_QUDT_NoOWL-v2.1.ttl)

...and optionally, if you want additional functionality, you could add:
[VOCAB_QUDT-DIMENSION-VECTORS-v2.1.ttl](https://github.com/qudt/qudt-public-repo/blob/main/vocab/dimensionvectors/VOCAB_QUDT-DIMENSION-VECTORS-v2.1.ttl)
[VOCAB_QUDT-CONSTANTS-v2.1.ttl](https://github.com/qudt/qudt-public-repo/blob/main/vocab/constants/VOCAB_QUDT-CONSTANTS-v2.1.ttl)

I'm happy to copy over the latest versions (with or without the optional extras) if you can confirm that they should be put in the "support" folder.

**The question:**
I'm unclear how you are doing your imports. Are they supposed to be resolving over the internet, or found in the "support" folder? Are the imports transitive?

**Comment by gtfierro** [comment]
Yes, they should be put in the `support` folder. Thanks for offering to do that! Feel free to push that directly to this branch

Currently the imports attempt to resolve the remote URI and before it tries to resolve locally. Thinking about this more, I think it might actually make more sense to prioritize local files over remote ones... I'll probably put that in a new release of the `ontoenv` tool that I'll incorporate into this PR.

**Comment by steveraysteveray** [comment]
Will do. And yes, I agree that looking for local files should definitely go first. Primarily because my experience is that industrial users want to maintain control over their versioning, and only move to newer versions after testing.

**Comment by steveraysteveray** [comment]
Done. Please note that the QUDT SHACL graph URI is http://qudt.org/2.1/schema/shacl/qudt. I don't want to mess up your framework, so I could use your help in updating the following files where http://qudt.org/2.1/schema/qudt is referenced:
- dependencies.gml
- mapping.json
- ontology.py
- qudt.ttl

I'm not sure which ones are autogenerated, and which ones are driving that.

Note that the prefix qudt: still expands to http://qudt.org/schema/qudt and all the defined entities still have that in the URI. That should not be changed.

**Comment by gtfierro** [comment]
`ontology.py` and `imports/qudt.ttl` will need to be changed -- the other two files are autogenerated from the `ontoenv` tool.

**Comment by steveraysteveray** [comment]
OK, ontology.py has been adjusted and pushed. Regarding qudt.ttl, what is this file? It looks like it is just a copy of the v2.1.12 OWL schema file for QUDT, which should be redundant with the SHACL schema file now in the support folder. Does anything feed off the qudt.ttl file?

**Comment by gtfierro** [comment]
I put it in there so the import tool would pull the definitions from there rather than pulling them remotely each time -- not something we really have to worry about though. Sounds like it is probably not the file we want though! Feel free to remove or replace with another copy of QUDT that actually contains the definitions we want

**Comment by steveraysteveray** [comment]
It looks like the imports folder and its contents are auto-generated when I run generate_brick.py. Not sure where it is getting the information.

**Comment by steveraysteveray** [comment]
I'm still confused. Maybe we could have a call sometime. Questions include:
1. You are planning to prefer local graphs to resolving over the internet, right? When will that be in place?
2. There is no imports folder in the repo. As far as I can tell, the whole folder is auto-generated. Did you mean to say that you put things like ref-schema and backnet in the support folder?
3. Assuming 1. above is true, how does the code recognize the URIs of the files/graphs in the imports folder?
4. What is the relationship between the imports folder and the support folder (where I placed the latest versions of the QUDT files), and how does the code recognize what is there?
5. If transitive dependencies are followed, then for QUDT it's simplest to just import http://qudt.org/2.1/vocab/unit (i.e. file VOCAB_QUDT-UNITS-ALL-v2.1.ttl), which will import everything else needed.

**Comment by gtfierro** [comment]
I'm out of town next couple days but we can do a meeting next week?

Some initial answers:

> You are planning to prefer local graphs to resolving over the internet, right? When will that be in place?

It is published in `ontoenv==0.3.5` so that should be available if you install it

> There is no imports folder in the repo. As far as I can tell, the whole folder is auto-generated. Did you mean to say that you put things like ref-schema and backnet in the support folder?

Yes, that's true -- this is what I get for trying to type up answers in an airport! Sorry for the confusion

The `ontoenv` tool should pick up any ontology definition (`<uri> a owl:Ontology`) anywhere in the repo; I'm centralizing the local copies of ontologies in `support/`. All of the imported ontologies are placed into `imports` so they can be zipped and distributed

**Comment by steveraysteveray** [comment]
I took the liberty of updating requirements.txt to call for ontoenv 0.3.5

I'm not yet convinced the import process is transitive, at least as reflected in the Brick+extensions.ttl file that is generated. However, things seem to be getting more stable.

Brick.ttl and Brick+extensions.ttl only show a couple of simple validation errors that I will track down.

**Pull request merged**
