### PR TITLE
Add EVSE Charging Concepts

### PR DESCRIPTION
**Pull request by gtfierro**
Addresses #517, but needs some additional work. @WesVerhagen let me know what you think! Most of the changes are in `equipment.py` and `entity_properties.py` -- just look for "Electric Vehicle"

Here's an example of the model (checked in under `examples/evse`)

```ttl
@prefix brick: <https://brickschema.org/schema/Brick#> .
@prefix unit: <http://qudt.org/vocab/unit/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix : <urn:evse#> .

:parking_lot a brick:Parking_Structure ;
    brick:isLocationOf :hub .

:hub a brick:Electric_Vehicle_Charging_Hub ;
    brick:hasPart :station1, :station2 .

:station1 a brick:Electric_Vehicle_Charging_Station ;
    brick:electricVehicleChargerType [ brick:value "Level 1" ] ;
    brick:hasPart :port1-1, :port1-2 ;
.

:port1-1 a brick:Electric_Vehicle_Charging_Port ;
    brick:electricVehicleConnectorType [ brick:value "Level 1 (SAE J1772)" ] ;
    brick:currentFlowType [ brick:value "AC" ] ;
    brick:electricalPhaseCount [ brick:value "1" ] ;
    brick:hasPoint :port1-1-voltage ;
.
:port1-1-voltage a brick:Battery_Voltage_Sensor ;
    brick:hasUnit unit:PERCENT ;
.

:port1-2 a brick:Electric_Vehicle_Charging_Port ;
    brick:electricVehicleConnectorType [ brick:value "Level 1 (SAE J1772)" ] ;
    brick:currentFlowType [ brick:value "AC" ] ;
    brick:electricalPhaseCount [ brick:value "1" ] ;
    brick:hasPoint :port1-2-voltage ;
.
:port1-2-voltage a brick:Battery_Voltage_Sensor ;
    brick:hasUnit unit:PERCENT ;
.

:station2 a brick:Electric_Vehicle_Charging_Station ;
    brick:electricVehicleChargerType [ brick:value "Level 2" ] ;
    brick:hasPart :port2-1 ;
.

:port2-1 a brick:Electric_Vehicle_Charging_Port ;
    brick:electricVehicleConnectorType [ brick:value "Level 2 (IEC 62196)" ] ;
    brick:currentFlowType [ brick:value "AC" ] ;
    brick:electricalPhaseCount [ brick:value "3" ] ;
    brick:hasPoint :port2-1-voltage ;
.

:port2-1-voltage a brick:Battery_Voltage_Sensor ;
    brick:hasUnit unit:PERCENT ;
.
```

### CODE REVIEW

**Comment by WesVerhagen** [comment]
Hi @gtfierro ,

Thank you for sharing the PR #529 and the example model for the Electric Vehicle Charging Hub. Overall, it looks good, and I appreciate the effort you put into it. I have just a few comments and suggestions:

1. **Bi-Directional Charging Property**: It would be beneficial to add a property to indicate whether the charger supports bi-directional charging. This can be useful for certain scenarios where the vehicle's battery can discharge back into the grid or other power storage systems.

2. **Missing Electric Vehicle Connector Types**: In the BRICK.ElectricVehicleConnectorTypeShape enumeration, it appears that some connector types are missing. Specifically, the "CSS Type 1" , "CSS Type 2"  and "GB/T" connectors are common standards used in certain regions. Adding these options to the enumeration would make the model more comprehensive.

3. **Wireless Charging Option**: Although wireless charging is not technically a "port," it might be beneficial to include it in the BRICK.ElectricVehicleConnectorTypeShape enumeration since it relates to charging methods and is becoming more popular in the EV industry.

Please address these points in the PR, and once you've made the updates, I'll take another look to ensure everything aligns with the project's requirements.

Thank you again for your contribution and dedication to improving the project. Looking forward to seeing the revised version.

Best regards,
Wes Verhagen

**Comment by gtfierro** [comment]
Hi @WesVerhagen . I've pushed the updates you requested. I've also added a rule that defaults a charging station to 'unidirectional' charging unless specified otherwise. One question -- does directionality exist on the charging station, on the hub, or on the port?

**Comment by WesVerhagen** [comment]
Hi @gtfierro 

Thank you for pushing the updates and implementing the changes I requested. I appreciate your prompt action.

The addition of the rule to default a charging station to 'unidirectional' charging unless specified otherwise is a valuable improvement. It will make the model more user-friendly and reduce the need for redundant data entry.

Regarding your question about directionality, it typically exists at the level of the charging port rather than the charging station or hub. The reason for this is that different ports on the same charging station or hub might support different charging capabilities. Some ports could be unidirectional, supporting charging only, while others could be bi-directional, enabling the vehicle's battery to discharge back into the grid.

By defining the directionality property at the port level, you allow for more granular control over the charging capabilities of individual ports on a single charging station or hub. This flexibility is essential, especially as EV charging technology continues to evolve and new standards are introduced.

Once again, thank you for your contributions and efforts in refining the model. Your dedication to the project is commendable!

Best regards,
Wes Verhagen

**Comment by gtfierro** [comment]
@WesVerhagen so sorry it has taken me this long to get back to the issue, but I have added in some inference rules that push the charging station's port directionality "down" to the ports if it is not specified on a port-by-port basis. It also adds unidirectional charging to the station by default (if the ports are not more specific)

**Comment by gtfierro** [comment]
TODO: add documentation on how the EVSE model works and what inferences are supported

**Pull request merged**
