### PR TITLE
Clarifying Point definitions

### PR DESCRIPTION
**Pull request by gtfierro**
Concentrating on On/Off, Start/Stop.

This draft PR holds implementations of the suggestions captured in the discussion at https://github.com/BrickSchema/Brick/issues/130

### CODE REVIEW

**Comment by jbkoh** [comment]
We already have a consensus for the Point top-classes: https://github.com/BrickSchema/Brick/issues/34. It was dropped somewhere. This PR should start from there unless we found any problem with the previous ones, which I am open to discuss.

**Comment by gtfierro** [comment]
I knew we had done definitions of the top level points before! Thanks for finding those. I incorporated those definitions and the ASHRAE dictionary definitions into some new text. Let me know what you think! I tried to be explicit about input/output nature of the points. It didn't make sense any more to me to adopt the ASHRAE definitions w/o alterations because some of the ASHRAE definitions do not directly address logical 'points' vs physical things e.g. sensors

**Comment by gtfierro** [comment]
@jbkoh any last edits on this before I merge it in?

**Comment by jbkoh** [comment]
I was adding top classes' definitions here: https://github.com/BrickSchema/Brick/commit/cec01b0cd22a7f9590d6089998437e7a16263d2a
but it would be easier to just add them here.

Other than that, I can't see the result of our discussion that we need to introduce more explicit class for Control_Loop_On_Off_Command == Start_Stop_Command. I have no strong opinion on keeping Start_Stop_Command or not. Do we wait for Ambuj to get back with a better idea on it?

**Comment by gtfierro** [comment]
We're not introducing new classes but rather clarifying the definitions and use of the ones that are already there. We can wait for additional input but we already have a few experts saying that they are fine with this classification

**Comment by jbkoh** [comment]
Our previous conclusion was to be explicit as much as possible. The "experts" might be fine with it because they internalized the difference between start_stop and on_off, which might not be generally true. I can still bear with it, if you prefer the implicit way,

**Comment by gtfierro** [comment]
I think we're in agreement here: `Start_Stop_{Command, Status}` is a term that is in use, hence why it appears in Brick. This PR is simply clarifying the definition of what that means in relation to existing concepts by (a) structuring the class hierarchy around what experts have agreed is a sensible interpretation of the terms, and (b) making both the structure and the actual definitions explicit in the definition of the Brick ontology. If there's other steps we can take, please let me know what you think they are and we can take them

**Comment by gtfierro** [comment]
Merging as of the approval on the Brick dev meeting today

**Pull request merged**
