### PR TITLE
Added new classes

### PR DESCRIPTION
**Pull request by carlosduarteroa**
Proposed the addition of new classes that I created based on going through the process of developing Brick models for three buildings. Two of the buildings have a [radiant heating and cooling system](https://en.wikipedia.org/wiki/Radiant_heating_and_cooling) for their primary HVAC system.

### CODE REVIEW

**Comment by epaulson** [comment]
Hi @carlosduarteroa - thanks for this, there's some really great work in here! We need to get the right folks to review this but we'll keep this moving!

**Comment by gtfierro** [comment]
@carlosduarteroa would you be able to submit a new PR that just has the radiant system classes in it? Or, perhaps more specifically, the classes that wouldn't be covered by the pending heat pump PRs? Let me know if I have it wrong and this doesn't actually make sense :)

**Comment by carlosduarteroa** [comment]
@gtfierro yeah, I'll be submitting multiple and smaller PRs to cover all the material that I had proposed in this giant PR and have not yet been proposed in another PR. I'll be submitting these in the next few days.

**Comment by gtfierro** [comment]
Beautiful! Let me know how I can help

**Comment by gtfierro** [comment]
Closing this issue because all of the other PRs have been successfully merged!

**Pull request closed without merging**
