### PR TITLE
Light Command to Lighting Command

### PR DESCRIPTION
**Pull request by jbkoh**
Resolving #439

### CODE REVIEW

**Comment by gtfierro** [comment]
Hope you don't mind but I just fixed the CSV file to have the trailing comma

**Comment by jbkoh** [comment]
Not at all. Thanks!

**Comment by jbkoh** [comment]
Sure, I'm fine with it.

**Comment by cbupp** [comment]
@jbkoh @gtfierro - reading through this discussion and the PR, I'm tempted to propose an alternative naming. I work with a team that sends many different commands to our fixtures. Light level (or sometime called dim level) is just one of those commands. We also send color change commands, sense commands (used during commissioning), and in some cases we send a command to alter the driver's modulation.

An alternative naming could be `Light_Level_Command`?

**Comment by cbupp** [comment]
Here's a related issue: [Add ColorTemperatureLightingCommand #445](https://github.com/BrickSchema/Brick/issues/445)

**Comment by jbkoh** [comment]
@cbupp Thanks for brining that up! I added a comment to the other thread, but Lighting Command presumed to change the levels but I think your idea of being more explicit is better. I will create a separate PR and close this one then.

**Comment by gtfierro** [comment]
@jbkoh is the plan still to close this PR and continue the development discussion?

**Comment by jbkoh** [comment]
Yes, let me close this one.

**Pull request closed without merging**
