### PR TITLE
Points about Points: Making Parameters Easier and More Expressive

### PR DESCRIPTION
**Pull request by gtfierro**
This is a newer cut at an issue that has come up a few times both in GitHub issues (https://github.com/BrickSchema/Brick/issues/142) and in conversations with the community. The linked issue has some helpful background.

This (in progress) PR implements a change to the `brick:Parameter` class organization that reduces the number of different parameter types and uses the `brick:isPointOf` relationship to relate limits and thresholds to the other points that they inform. A setpoint Point entity would have max/min setpoint limit Point entities associated with it that would capture the maximum/minimum allowed value of the setpoint. An alarm Point entity would have high/low threshold Point entities associated with it that would capture the thresholds at which an alarm is triggered

This has two benefits:
- reduces the number of classes that users have to be familiar with, simplifies the hierarchy
- use of `isPointOf` makes it explicit which limits/thresholds relate to which points

Two examples contrasting the existing and proposed design are below. Both describe setpoints with max/min limits. All entities in the `orig:` namespace follow the Brick 1.2 design as it stands today. all entities in the `new:` namespace follow the proposed design

```ttl
@prefix brick: <https://brickschema.org/schema/Brick#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix orig: <urn:orig#> .
@prefix new: <urn:new#> .

################## scenario 1

orig:zone   a brick:HVAC_Zone .
orig:sp     a   brick:Temperature_Setpoint .
orig:sen     a   brick:Temperature_Sensor .
orig:max    a brick:Max_Temperature_Setpoint_Limit .
orig:min    a brick:Min_Temperature_Setpoint_Limit .

orig:vav    a   brick:VAV ;
    brick:feeds orig:zone ;
    brick:hasPoint  orig:sp, orig:sen, orig:max, orig:min ;
.

new:zone   a brick:HVAC_Zone .
new:sp     a   brick:Temperature_Setpoint .
new:sen     a   brick:Temperature_Sensor .
new:max    a brick:Max_Setpoint_Limit ;
    brick:isPointOf new:sp .
new:min    a brick:Min_Setpoint_Limit ;
    brick:isPointOf new:sp .

orig:vav    a   brick:VAV ;
    brick:feeds orig:zone ;
    brick:hasPoint  orig:sp, orig:sen, orig:max, orig:min ; # last 2 are optional
.



################## scenario 2

orig:ahu    a   brick:AHU;
    brick:hasPoint  orig:occ_cool_dis_afsp, orig:unocc_cool_dis_afsp, 
                    orig:occ_heat_dis_afsp, orig:unocc_heat_dis_afsp,
                    orig:min_occ_cool_dis_afsp, orig:min_unocc_cool_dis_afsp, 
                    orig:min_occ_heat_dis_afsp, orig:min_unocc_heat_dis_afsp,
                    orig:max_occ_cool_dis_afsp, orig:max_unocc_cool_dis_afsp, 
                    orig:max_occ_heat_dis_afsp, orig:max_unocc_heat_dis_afsp ;
.

orig:occ_cool_dis_afsp a brick:Occupied_Cooling_Discharge_Air_Flow_Setpoint .
orig:unocc_cool_dis_afsp a brick:Unoccupied_Cooling_Discharge_Air_Flow_Setpoint .
orig:occ_heat_dis_afsp a brick:Occupied_Heating_Discharge_Air_Flow_Setpoint .
orig:unocc_heat_dis_afsp a brick:Unoccupied_Heating_Discharge_Air_Flow_Setpoint .
orig:min_occ_cool_dis_afsp a brick:Min_Occupied_Cooling_Discharge_Air_Flow_Setpoint_Limit .
orig:min_unocc_cool_dis_afsp a brick:Min_Unoccupied_Cooling_Discharge_Air_Flow_Setpoint_Limit .
orig:min_occ_heat_dis_afsp a brick:Min_Occupied_Heating_Discharge_Air_Flow_Setpoint_Limit .
orig:min_unocc_heat_dis_afsp a brick:Min_Unoccupied_Heating_Discharge_Air_Flow_Setpoint_Limit .
orig:max_occ_cool_dis_afsp a brick:Max_Occupied_Cooling_Discharge_Air_Flow_Setpoint_Limit .
orig:max_unocc_cool_dis_afsp a brick:Max_Unoccupied_Cooling_Discharge_Air_Flow_Setpoint_Limit .
orig:max_occ_heat_dis_afsp a brick:Max_Occupied_Heating_Discharge_Air_Flow_Setpoint_Limit .
orig:max_unocc_heat_dis_afsp a brick:Max_Unoccupied_Heating_Discharge_Air_Flow_Setpoint_Limit .


new:ahu    a   brick:AHU;
    brick:hasPoint  new:occ_cool_dis_afsp, new:unocc_cool_dis_afsp, 
                    new:occ_heat_dis_afsp, new:unocc_heat_dis_afsp,
                    new:min_occ_cool_dis_afsp, new:min_unocc_cool_dis_afsp, 
                    new:min_occ_heat_dis_afsp, new:min_unocc_heat_dis_afsp,
                    new:max_occ_cool_dis_afsp, new:max_unocc_cool_dis_afsp, 
                    new:max_occ_heat_dis_afsp, new:max_unocc_heat_dis_afsp ;
.

new:occ_cool_dis_afsp a brick:Occupied_Cooling_Discharge_Air_Flow_Setpoint ;
    brick:hasPoint  new:min_occ_cool_dis_afsp, new:max_occ_cool_dis_afsp .
new:min_occ_cool_dis_afsp a brick:Min_Setpoint_Limit .
new:max_occ_cool_dis_afsp a brick:Max_Setpoint_Limit .

new:unocc_cool_dis_afsp a brick:Unoccupied_Cooling_Discharge_Air_Flow_Setpoint ;
    brick:hasPoint  new:min_unocc_cool_dis_afsp, new:max_unocc_cool_dis_afsp .
new:min_unocc_cool_dis_afsp a brick:Min_Setpoint_Limit .
new:max_unocc_cool_dis_afsp a brick:Max_Setpoint_Limit .

new:occ_heat_dis_afsp a brick:Occupied_Heating_Discharge_Air_Flow_Setpoint ;
    brick:hasPoint  new:min_occ_heat_dis_afsp, new:max_occ_cool_dis_afsp .
new:min_occ_heat_dis_afsp a brick:Min_Setpoint_Limit .
new:max_occ_heat_dis_afsp a brick:Max_Setpoint_Limit .

new:unocc_heat_dis_afsp a brick:Unoccupied_Heating_Discharge_Air_Flow_Setpoint ;
    brick:hasPoint  new:min_unocc_heat_dis_afsp, new:max_unocc_cool_dis_afsp .
new:min_unocc_heat_dis_afsp a brick:Min_Setpoint_Limit .
new:max_unocc_heat_dis_afsp a brick:Max_Setpoint_Limit .
```

### CODE REVIEW

**Comment by gtfierro** [comment]
@jbkoh @epaulson it would be great to get your thoughts on the above design!

**Comment by jbkoh** [comment]
I like the design in general, but I think `hasPoint` is already overloaded with many use cases, which 1) confuses users and 2) complicates system implementations in practice. We should rather introduce a dedicated term for this. Maybe `hasParameter` (which is not a subproperty of `hasPoint`.)

And do we plan to expand this concept to any parameters or just limit to min/max?
If it's true, what kind of parameter hierarchy do we want to preserve?
If it's not true, why min/max so special?

**Comment by gtfierro** [comment]
This has come up in the isPointOf/hasLocation thread on the forum, but `hasPoint` is generally for the association of telemetry with what it is "about". In that sense, the "points about points" use case here strikes me as an appropriate use of that property. I think a subproperty of `hasPoint` like `hasParameter` could make the semantics more precise.

Good questions about how to generalize. I'm not sure how many of the other parameters are actually about other points. Most of them seem to be about PID controllers and control strategies. There's definitely a need to bring some more structure to the rest of the parameter hierarchy, but I'm not sure if the design proposed here would help.

**Comment by jbkoh** [comment]
Sorry it took such a long time to get back to this. I don't see a benefit of using a generic property name instead of precise property name. Are there cases where an application wants to query `hasPoint` across different entity types? Otherwise, why bother overloading the meaning to confuse users?

**Comment by gtfierro** [comment]
`hasPoint` relates an entity to telemetry about that entity. How do you feel about a `hasParameter` property that is a subproperty of `hasPoint`?

**Comment by jbkoh** [comment]
I understand that the proposal is not conflicting `hasPoint`'s meaning. I just think our usage of `hasPoint` is too generic to be useful. `hasParameter` is fine, but subPropertyOf is quite difficult to implement in practice cosidering various CRUD operations online. E.g., there isn't a good and performative RDF store that supports inference at query time to avoid such complication. So, I'd get away form subPropertyOf unless it's really useful. In this case, I don't see a strong use case (unlike feeds > feedsAir).

**Comment by jbkoh** [comment]
I take back on the hasPoint vs hasParameter issue, and I'm fine with hasParameter being a subproperty of hasPoint. 

However, I just realized that this PR contains too many breaking changes to be in the next minor version update. I'd vote for introducing the points-about-points concept but keeping the existing classes for now.

**Comment by gtfierro** [comment]
TODOs:
- check in with 223P for their min/max limit model
- deprecate, not remove, the existing parameter classes

**Pull request closed without merging**
