### PR TITLE
Fix a bug: non-substances being Substances

### PR DESCRIPTION
**Pull request by jbkoh**
- Bug1: Remove Luminance and Enthalpy being subclasses of Substance, which are Quantities.
- Bug2: Wrong tags as ``brick"Location brick:hasTag tag:Loc`` as ``brick:Equipment brick:hasTag tag:Equip``.

### CODE REVIEW

**Comment by gtfierro** [comment]
Should these be quantities rather than substances?

**Comment by jbkoh** [comment]
Luminance is a Quantity and Light would be a Substance
(https://en.wikipedia.org/wiki/Luminance)
Enthalpy as well; "Enthapy is a property of thermodynamic system" (https://en.wikipedia.org/wiki/Enthalpy)

You defined them in both substances.py and quantities.py.

**Comment by gtfierro** [comment]
Ok, lets move them into quantities, and then introduce Light as a substance.

---

Changing `Loc` and `Equip` tags should go into its own PR.

**Comment by jbkoh** [comment]
That's a separate PR but didn't file it. I will submit that first and then accept this.

**Comment by jbkoh** [comment]
It's hard to separate them out for now. I just added the change in the PR request too.

**Comment by gtfierro** [comment]
Its not that hard to separate them out. If you're not comfortable editing the branches in git, you can just create two new branches and copy/paste the changes there. Its important to keep these changes isolated

**Comment by jbkoh** [comment]
I created a separate branch for the later one but because the commit history follows, it shows up in this PR anyway. Otherwise, I have to create new commits separately for those two, which just takes time. I will do it when I find the time, if you don't like.

**Comment by gtfierro** [comment]
Looks great! Thanks for taking the time to separate the two changes

**Comment by jbkoh** [comment]
You are welcome. Thanks for the suggestions!

**Pull request merged**
