### PR TITLE
Better structure for defining extensions to Brick

### PR DESCRIPTION
**Pull request by gtfierro**
See `demo_extension/new_sensors.py` for an example. Run with `python generate_brick.py demo_extension.new_sensors`

TODO: make sure there is some way of specifying what version of the Brick ontology an extension is expected to work with (maybe min/max Brick versions?)

### CODE REVIEW

**Comment by steveraysteveray** [comment]
A couple of comments.
1. I tried running the command you mentioned. I think there's a typo. Shouldn't it be "Run with python generate_brick.py demo_extension.new_sensors" (i.e. extension, not extensions?)
2. What should I see being created? A new Brick+extensions.ttl or something like that? I'm not seeing it, and I'm getting an error: ModuleNotFoundError: No module named 'demo_extension.new_sensors.py'; 'demo_extension.new_sensors' is not a package
3. I'm anxious to see how this plays with the 223 changes found in branch srr-cleanup-223-extension (MR #523).  Is that feasible?

**Comment by gtfierro** [comment]
> A couple of comments.
> 
> 1. I tried running the command you mentioned. I think there's a typo. Shouldn't it be "Run with python generate_brick.py demo_extension.new_sensors" (i.e. extension, not extensions?)

Yes! Sorry -- that's my typo

> 2. What should I see being created? A new Brick+extensions.ttl or something like that? I'm not seeing it, and I'm getting an error: ModuleNotFoundError: No module named 'demo_extension.new_sensors.py'; 'demo_extension.new_sensors' is not a package

You should see a new .ttl file at "extensions/demo_extension/new_sensors.ttl". This is the output I get when running the "python generate_brick.py demo_extension.new_sensors"

```
python generate_brick.py demo_extension.new_sensors                                         
2023-07-20:09:37:31,594 WARNING [generate_brick.py:294] Property 'tags' not defined for https://brickschema.org/schema/Brick#Measurable
2023-07-20:09:37:31,595 WARNING [generate_brick.py:294] Property 'tags' not defined for https://brickschema.org/schema/Brick#Measurable
2023-07-20:09:37:32,037 WARNING [generate_brick.py:294] Property 'tags' not defined for https://brickschema.org/schema/Brick#Lighting
2023-07-20:09:37:32,552 WARNING [generate_brick.py:731] WARNING: Close_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#Close_Limit.
2023-07-20:09:37:32,595 WARNING [generate_brick.py:731] WARNING: Current_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#Current_Limit.
2023-07-20:09:37:32,597 WARNING [generate_brick.py:731] WARNING: Position_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#Position_Limit.
2023-07-20:09:37:32,599 WARNING [generate_brick.py:731] WARNING: Position_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#Max_Position_Setpoint_Limit.
2023-07-20:09:37:32,600 WARNING [generate_brick.py:731] WARNING: Position_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#Min_Position_Setpoint_Limit.
2023-07-20:09:37:32,610 WARNING [generate_brick.py:731] WARNING: Fresh_Air_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#Fresh_Air_Setpoint_Limit.
2023-07-20:09:37:32,612 WARNING [generate_brick.py:731] WARNING: Fresh_Air_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#Min_Fresh_Air_Setpoint_Limit.
2023-07-20:09:37:32,614 WARNING [generate_brick.py:731] WARNING: Fresh_Air_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#Max_Fresh_Air_Setpoint_Limit.
2023-07-20:09:37:32,616 WARNING [generate_brick.py:731] WARNING: Ventilation_Air_Flow_Ratio_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#Ventilation_Air_Flow_Ratio_Limit.
2023-07-20:09:37:32,626 WARNING [generate_brick.py:731] WARNING: High_Static_Pressure_Cutout_Setpoint does not exist in Brick for https://brickschema.org/schema/Brick#High_Static_Pressure_Cutout_Setpoint_Limit.
Reading in entity properties and/or class definitions from demo_extension.new_sensors
2023-07-20:09:37:32,647 WARNING [generate_brick.py:294] Property 'tags' not defined for urn:demo_extension#Sensor_Platform
2023-07-20:09:37:32,647 WARNING [generate_brick.py:294] Property 'tags' not defined for urn:demo_extension#PurpleAir_Weather_Station
Writing extension graph to extensions/demo_extension/new_sensors.ttl 
```

(and then some other extra output)

Weird that you're getting some sort of import error. What version of Python are you using? Does the error go away if you create an empty "__init__.py" file inside the demo_extension folder?

> 3. I'm anxious to see how this plays with the 223 changes found in branch srr-cleanup-223-extension (MR [Srr cleanup 223 extension #523](https://github.com/BrickSchema/Brick/pull/523)).  Is that feasible?

I've merged in your srr-cleanup-223-extension branch into a copy of this branch and put it in a new gtf-allow-extensions-with-223 branch. So far it seems to work ok together

**Comment by steveraysteveray** [comment]
Great! Not sure what changed, but after a git pull, "python generate_brick.py demo_extension.new_sensors" seems to be working.

So my question is what the procedure now? I know we handle graph imports slightly differently, but is the idea that new_sensors.ttl would import Brick.ttl, (or vice-versa)?

For the 223 extension, is handle_extensions.py still part of the procedure? Will there be 

1. a Brick+extensions.ttl file in the future, or
2. a 223 file generated by a Python script similar to new_sensors.py, or
3. Brick.ttl just importing extensions/brick_extension_s223_extension.shapes.ttl

**Comment by steveraysteveray** [comment]
Related to extensions in general,  the Brick+extensions.ttl file needs a couple of tweaks:
1. It contains 4 ontology declarations that, while allowed, produces unpredictable effects in at least some environments. Recommend we choose one declaration (could even be the original Brick declaration, as long as it doesn't have to co-exist with the non-extended version).
2. Related to the above, my environment is not successfully resolving the prefix definitions for the SPARQLConstraints and SPARQLRules. After manually editing Brick+extensions.ttl to have only a single ontology declaration, and having all sh:prefixes statements point to that ontology (containing the sh:declare statements), everything seems to work for reasoning and validation.

**Comment by gtfierro** [comment]
Thanks for your patience on this @steveraysteveray!

I just pushed a fix that should address the issues you are seeing with the 'Brick+extensions.ttl' file. The `handle_extensions.py` file just does all of the `sh:declare`/`sh:prefixes`/`owl:Ontology` edits.

The method of defying extensions that I'm introducing here is really for people that are extending Brick's classes/properties/etc -- the file structure is intentionally rigid to make these extensions easy to maintain for common used cases, such as adding proprietary equipment classes to Brick. I would imagine the 223P extension stuff stays how it is now -- something like that is probably better maintained as Turtle files. So, to answer your question, `handle_extensions.py` is definitely still part of the picture.

**Comment by steveraysteveray** [comment]
OK. Did some tests after merging in (locally) the gtf-allow-extensions-with-223 branch. What's odd is that at least for me, none of the extension file contents show up in Brick+extensions.ttl. I see your code in handle_extensions.py:
```
# add extension files to Brick graph
extension_files = glob.glob("extensions/*.ttl")
for filename in extension_files:
    brick_graph.parse(filename)
```
...where I assumed that happens. Do you get all the extension contents in your copy?

In the meantime, I manually imported <https://brickschema.org/extension/s223extension> and then everything seems to work beautifully, so I feel we are oh so close!

**Comment by steveraysteveray** [comment]
I take it back! Tried reproducing my problems, and now everything works!

**Comment by gtfierro** [comment]
Thanks for checking! I'll merge this once the tests pass

**Comment by steveraysteveray** [comment]
I did some cleanup of the extensions folder in branch srr-cleanup-223-extension so as not to depend on the import statements. I then tested everything using a local test branch that merged in srr-cleanup-223-extension, gtf-allow-extensions and gtf-allow-extensions-with-223. I think things are stable. Once you have merged all three branches into master, then I will update the 223 files from the latest 223 repo into the Brick extensions folder (so that some of the recent Equipment updates are incorporated, among other things). Lots of moving parts right now, so it will be good to stabilize.

**Pull request merged**
