### PR TITLE
Limit subproperty inference to entity properties

### PR DESCRIPTION
**Pull request by gtfierro**
Address #472

### CODE REVIEW

**Comment by gtfierro** [comment]
@jbkoh @epaulson do you have any issues with this fix? @steveraysteveray laid out the issues w/ sub property inference in #472. It's not an issue for Brick, but by making our inference rule more specific, Brick can be a better "ontology citizen" when integrated with other ontologies.

**Comment by jbkoh** [comment]
I'm fine with the changes!

**Review by jbkoh — APPROVED** [review]

**Comment by steveraysteveray** [comment]
As long as you don't nest rdfs:subPropertyOf more than 1 level deep this works in a single iteration. Otherwise, you could add a + to the rdfs:subPropertyOf predicate, or assume iterative reasoning.

**Comment by gtfierro** [comment]
Are the defaults semantics for reasoning not fixed point? I'm pretty sure that pySHACL iterates it's rules a number of times until the graph stops changing. If the reasoning is not fixed point by default, then I agree it would be better to use the transitive closure here. Probably more performant anyway, too!
________________________________
From: steveraysteveray ***@***.***>
Sent: Thursday, January 26, 2023 8:48:29 AM
To: BrickSchema/Brick ***@***.***>
Cc: Gabriel Fierro ***@***.***>; Author ***@***.***>
Subject: [External] Re: [BrickSchema/Brick] Limit subproperty inference to entity properties (PR #473)

CAUTION: This email originated from outside of the Colorado School of Mines organization. Do not click on links or open attachments unless you recognize the sender and know the content is safe.


As long as you don't nest rdfs:subPropertyOf more than 1 level deep this works in a single iteration. Otherwise, you could add a + to the rdfs:subPropertyOf predicate, or assume iterative reasoning.

**Comment by steveraysteveray** [comment]
Not the default in TBC, although I always set it to iterate. The [SHACL Advanced Features spec](https://w3c.github.io/shacl/shacl-af/#rules-execution) seems to be non-committal one way or the other.

**Comment by steveraysteveray** [comment]
Looks good to me!

**Pull request merged**
