### PR TITLE
fix a wrong hierarchy

### PR DESCRIPTION
**Pull request by jbkoh**
`Hot_Water_Differential_Temperature_Sensor` should not be a subclass of leaving temperature and entering temperature even if they are related with each other.

### CODE REVIEW

**Comment by gtfierro** [comment]
Sounds like a good change to me!

**Comment by jbkoh** [comment]
Thanks. Btw, why does the unit test take forever? 4 hours unit testing is way too long for an individual contributor to iterate development

**Comment by gtfierro** [comment]
That is a great question and a discussion for another time! It essentially comes down to reasoning

**Comment by gtfierro** [comment]
@jbkoh is this PR ready for review?0

**Pull request closed without merging**
